### ISSUE TITLE
I'm trying to use the library however I get an issue when trying to install it

### ISSUE THREAD

**Issue by nikivdev** [jason0x43/go-alfred#1]
Here is what I get when I run go install command : 

![2016-07-19 at 23 50](https://cloud.githubusercontent.com/assets/6391776/16967859/9331ccd2-4e0b-11e6-8fe6-6d18f397e813.png)

Perhaps I have made some mistake. Thank you for any help.

**Comment by jason0x43** [comment]
Try `go get github.com/jason0x43/go-alfred/alfred`

**Comment by jason0x43** [comment]
Just cleaning house -- is this still an issue?

**Comment by nikivdev** [comment]
No it isn't anymore. Thank you.
