### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by bikenik** [jason0x43/go-alfred#11]
Hello!
I'm getting this after any commands:
```
goroutine 1 [running]:
main.getPrefsDirectory(0x137aed5, 0xc)
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:203 +0x5d5
main.main()
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:95 +0xa5
```
Thnx for any suggestions in advance.

/ go version go1.10 darwin/amd64 /

**Comment by jason0x43** [comment]
The app wasn't properly handling the case where a sync folder hand't been setup for Alfred. I pushed an update (commit https://github.com/jason0x43/go-alfred/commit/74b4042c77c1ba9d3edc9a4c87134ca39292b8bb) that should take care of that. Give it a try.

**Comment by bikenik** [comment]
<kbd>`alfred build`</kbd> now is working 
it's most crucial for me - Thank you!

---
- <kbd>alfred link</kbd>
#### panic: runtime error: invalid memory address or nil pointer dereference
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12cc463]

goroutine 1 [running]:
main.fileExists(0xc4201e65b0, 0x6c, 0x3)
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:577 +0x83
main.getExistingInstall(0x0, 0x0, 0x0, 0x0)
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:319 +0x29b
main.link()
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:373 +0x119
main.main()
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:141 +0x634
```

- <kbd>alfred unlink</kbd>
removed link alfred-test-workflow
#### panic: runtime error: invalid memory address or nil pointer dereference
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12cc463]

goroutine 1 [running]:
main.fileExists(0xc42032aa10, 0x6c, 0x3)
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:577 +0x83
main.getExistingInstall(0x0, 0x0, 0x0, 0x0)
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:319 +0x29b
main.unlink()
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:515 +0x15d
main.main()
	/Users/user/go/src/github.com/jason0x43/go-alfred/alfred/main.go:147 +0x744
```

**Comment by jason0x43** [comment]
You're just uncovering all the fun errors today. :) In this case, code checking for file or directory existence was trying to use a FileInfo structure when it wasn't valid.

I pushed a new commit that should take care of that. Let's see how far that gets you. It seems like there are some fundamental differences between your filesystem layout and mine as it relates to Alfred, so you may run into more issues.

**Comment by bikenik** [comment]
This will be my start to "go" :) and as I said <kbd>alfred build</kbd> is allow me to do this. I guess that it's enough to be going on with for me. Thnx.

---

 [e16fb](https://github.com/jason0x43/go-alfred/commit/e16fbe6dd35e5b8542356fa05d101e0724985c99) resolved in my case
