### ISSUE TITLE
How do you link development with Alfred itself?

### ISSUE THREAD

**Issue by nikivdev** [jason0x43/go-alfred#4]
Since all go projects have to be developed in $GOPATH, if I create a directory with the workflow I will be developing in the $GOPATH, how do I then easily test it out in Alfred?

**Comment by nikivdev** [comment]
Perhaps there should be a function that would build the workflow into a binary and then transfer the binary to the directory location? Or perhaps there is a better way to do it.

**Comment by jason0x43** [comment]
Assuming you have built and installed the `alfred` binary (`go install github.com/jason0x43/go-alfred/alfred`), and that your workflow development directory contains a `workflow` subdirectory, you can run `alfred link` to link the workflow directory to a location visible to Alfred.

**Comment by jason0x43** [comment]
My typical structure looks like:

```
<project>/
    main.go
    // other go files
    workflow/
        info.plist
        icon.png
```

Running `alfred build` builds your workflow binary into the `workflow` directory. Running `alfred link` basically "installs" the `workflow` directory. From then on, whenever you run `alfred build`, you'll immediately be using the new binary when you use your workflow in alfred.

**Comment by nikivdev** [comment]
Can you expand a little on the 'link the workflow directory to a location visible to Alfred'

For example I have a very simple main.go file that shows some output in Alfred. I entered 'alfred link' and got this : 

![2017-02-20 at 23 41](https://cloud.githubusercontent.com/assets/6391776/23144168/17b4ac90-f7c6-11e6-8f39-928f5a7aa65f.png)

Then if I press alfred build, it should transfer a binary there if I understand correctly?

Also how did it get this user.workflow.C8E62A7E-4AEF-4A8A-B38C-B9E53AC71C05?

**Comment by nikivdev** [comment]
Is my project structure. 

![2017-02-20 at 23 42](https://cloud.githubusercontent.com/assets/6391776/23144190/41755444-f7c6-11e6-9f47-a47f22f24ced.png)

**Comment by nikivdev** [comment]
I think I understood it by reading the [code](https://github.com/jason0x43/go-alfred/blob/master/alfred/main.go). So it gets the workflow directory open in alfred preferences? This one : 

![2017-02-20 at 23 44](https://cloud.githubusercontent.com/assets/6391776/23144248/88cdd0aa-f7c6-11e6-9477-df3f5f0ad59e.png)

**Comment by nikivdev** [comment]
But in this case it actually linked the wrong workflow. It linked something else.

**Comment by nikivdev** [comment]
I unlinked it and to link again making sure I have the workflow 'a: markdown parser' open and it still links the wrong workflow. :(

**Comment by jason0x43** [comment]
When Alfred installs a workflow, it installs the workflow files in a directory based on a randomly generated value (a UUID). The `link` command does something similar -- it creates a symbolic link from your development workflow directory to a randomly generated `user.workflow.<UUID>` directory in Alfred's normal workflow installation location. From Alfred's perspective, this is pretty much the same as installation.

Since the uuid value is randomly generated, there is almost zero chance of `link` trying to associate your workflow with a pre-existing workflow.

Note that your workflow will probably also need an info.plist file for Alfred to recognize it.

**Comment by nikivdev** [comment]
This clears everything up. Thank you. 

Is there anything I can use to generate this info.plist file?

**Comment by jason0x43** [comment]
I've typically created an empty workflow in Alfred, opened it in Finder, and taken its info.plist. Not the most elegant solution.

**Comment by nikitavoloboev** [comment]
mmm

**Comment by nikivdev** [comment]
This is really amazing, thank you.
