### ISSUE TITLE
Some help with using the library to make a workflow

### ISSUE THREAD

**Issue by nikivdev** [jason0x43/go-alfred#5]
I would like to make a workflow that would allow me to fuzzy select through various websites to make a search. I wrote a bit more about it [here](https://www.alfredforum.com/topic/10043-i-want-to-transfer-all-my-web-searches-into-a-script-filter-for-fuzzy-matching/#comment-50410).

What I don't get is how to do this with this library. I am thinking of creating a list of web queries and put it in some kind of struct. But I am not really sure how to even add items to the script filter with this workflow. 

It says I have to use the method Add and it takes in an Item as argument but how do I generate this Item since it has so many fields. I am not really sure.

Thank you for any help. 

If I can figure out how to use this library and would solve this problem I have, it would solve me hours of my time.

**Comment by jason0x43** [comment]
Sorry about the lack of documentation; I wasn't aware anyone else was using this, so I didn't spend a lot of time on that. :)

The easiest thing might be to look at one of my workflows that uses this library, like https://github.com/jason0x43/alfred-weather or https://github.com/jason0x43/alfred-toggl.

Basically, you create a Workflow object and then run it with a list of Commands. A Command must have an About method, and can have Items (to return a list) and Do (to do something) methods. The Items method just returns an array of Item structs. There's nothing really special there; it's just a simple array of structs (not pointers).
