### ISSUE TITLE
How does alfred pack pick a version?

### ISSUE THREAD

**Issue by nikivdev** [jason0x43/go-alfred#6]
I want to use `alfred pack` command to create my .alfredworkflow file that I can then attach to GitHub releases.

However it creates the .alfredworkflow file with the wrong version. Is it possible for it to create the file with the version I specify in the workflow here : 

![2017-09-14 at 03 26](https://user-images.githubusercontent.com/6391776/30408029-7f5f3018-98fc-11e7-99e7-58da1f9edd2d.png)

**Comment by jason0x43** [comment]
The `pack` command doesn't do anything regarding the package version, it simply zips up the workflow directory into an .alfredworkflow file. Whatever version is currently in the info.plist (which corresponds to the field you've indicated above) is what ends up in the .alfredworkflow file.

**Comment by jason0x43** [comment]
Closing this since it seems to be answered, but feel free to reopen.
