### ISSUE TITLE
Is it possible to replace symlinks if they were already made for a workflow?

### ISSUE THREAD

**Issue by nikivdev** [jason0x43/go-alfred#9]
I am using your [Alfred](https://godoc.org/github.com/jason0x43/go-alfred/alfred) CLI tool and really like it.

So much that I even advise people who want to hack on my workflow to use it to bootstrap working on the it.

[Here](https://github.com/nikitavoloboev/alfred-web-searches#developing) are the instructions I say on all my workflows so far.

However there is a problem. If the person downloaded my workflow to their system. And then wishes to develop some new features. He git clones my repository with the code like [this one](https://github.com/nikitavoloboev/alfred-web-searches). But then running `alfred link` will create ANOTHER workflow in the Alfred Preferences of the user. 

Is it possible to somehow make this work without this problem? Thank you for any help.

**Comment by jason0x43** [comment]
So, a user has installed your workflow normally, and has also cloned the repo and `alfred link`'ed it?

**Comment by nikivdev** [comment]
Yes. Essentially I want the most painless way to bootstrap working on a Go workflow for newcomers without any conflicts.

**Comment by jason0x43** [comment]
The `link` command _could_ do something here, although I'm not sure it _should_. I mean, if a user has installed a copy of one of your workflows and wants to replace it with a development version, it's pretty simple to delete the existing workflow in Alfred. If a user wants to create a new workflow using an existing workflow as a template, though, they may want to keep both the original and the new development version.

One possibility would be for the `link` command to scan the workflows directory and find any existing copies of the current workflow and offer to delete them.

**Comment by nikivdev** [comment]
> One possibility would be for the link command to scan the workflows directory and find any existing copies of the current workflow and offer to delete them.

This sounds great indeed. I am just thinking for a newcomer, if he saw two `same` workflows, it would be really confusing. Also it's not immediate which one is development version and which one is not.

**Comment by jason0x43** [comment]
If the `link` command were to delete existing copies of the workflow, they would actually be deleted (not just unlinked), which would mean a user would have to re-download and install them later if they wanted the original workflow back. That's probably not a significant issue, though.

**Comment by nikivdev** [comment]
Yeah I think that's better though. We can inform the user when that happens though perhaps?

**Comment by nikivdev** [comment]
Although I am thinking if it might cause problems. So my goal is to provide simple working instructions on working on a Go workflow. Like your Toggl workflow for example. 

So currently [this is what I have](https://github.com/nikitavoloboev/alfred-web-searches#developing) and if you add the change that `link` swaps the workflow with development version I think it would be good.

So person hacks on some changes and maybe submits a PR. I accept it and then workflow updates. He would then get update notification and new workflow loads. Will he still have the links from his cloned repo. I think he wouldn't right?

The problem I see with it is that let's say a person is hacking on one of my workflows and then in the middle of it, I issue an update. So he loads it and he loses all changes he made?

**Comment by jason0x43** [comment]
It seems like the options are to maintain two copies of a workflow (assuming the developer is working on yours rather than trying to create something new), or replace the published version one with the git cloned version. If a user maintains 2 copies of the workflow, he'd probably _want_ to change the name of the dev version, and he'd _need_ to change the keywords, or the two workflows would clash. That's going to be a pain, so the simplest thing from a usability standpoint is probably to only have one copy of the workflow.

Given that, link should probably point out that there's an existing copy and offer to delete it.

When the user switches to a developer workflow, they should be using git to get workflow updates rather than having the workflow update itself. Having a workflow self-update (at least in they way my workflow lib handles it) won't remove the developer version of the code, but it will result in two copies of the workflow being installed (not a huge deal, but annoying).

**Comment by nikivdev** [comment]
> so the simplest thing from a usability standpoint is probably to only have one copy of the workflow.

I agree. I think this is better.

**Comment by nikivdev** [comment]
Just wanted to ask if you had any time to look at this? Would really appreciate this little change.

**Comment by jason0x43** [comment]
I pushed an update for this. What I ended up doing is disabling any existing copy of the workflow (the first one that's found), which leaves it in place but inactive. When unlinking a development workflow, the existing disabled copy (if there is one) will be re-enabled.

**Comment by jason0x43** [comment]
Closing this for now. If it's still an issue, let me know.
